travis:
  secure:
    BINSTAR_TOKEN: iRk5+cJUt2kXvkCOM3eARjKANad7whhEQHuCOl/CYLCtWJsd7n4TQBL8OGP1XL+j/YHRZCtakJz0mc/zmuypUSyyK1nkLggIzqD00ay1Ci25SXQj8PJO9fv/PhiNfPVEwJZYJRg1IMp5ZesOwJxaMTPlwgZljnWyd8WnwoG98j3El29vJ42zZLq8vfTaUYPjb6IFFuuAf/Tj4iildhnOl5q6q9ECIuNWHdhT8gb0jw6J9qPYTi2UwqqXYCYfYQInXzVYXD3CqusbixNgokea2WByS4aesoVMACsODFQG4q2RjevTk51JR+N8JPfsawFHcxwa0t7Sdh8PmN2hk08u5yP7nR3aSe1l+KxlSI6as4qCs9gGKm+vVdC057Xc2hhqGIrwTo31o3FhIEgFV5xvAK+JALpcoSEOXcDVnIE72+wT7fcm8TcXiOisyHFeaynv+vpbMBChkktxeC897vjl3l2zhHCtix/TUxoMxWdPX/n/z2xvBPvGd/U1jJtU38nbhJ4aABUMH5O/8XZ1MRjj9/LhzXFypmvCmpFUY4Qg92TM6yWBexuadF+SFe+lTdc1CjX7e3uCbATdnNkRZmuZVhuQwUoUvwL1AC+dvXDmV4VoMBsFL9al4B2Iabr1pTGW4g++MXOes2Romq1zrJC6re7SWX090hG+bNijPonsoWQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
